[package]
name = "chordflow_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
anyhow = "1.0.95"
strum = { version = "0.27.0", features = ["derive"] }
rand = "0.9.0"
strum_macros = "0.27.0"
chordflow_music_theory = {path = "../chordflow_music_theory/"}
